# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08a55a28a29c266fc4fb550dbc1f13cf7dc19653a89acbca45c98b389521582c1b66b26529005e96ddeffcbdef1607f2347c7468d3102db5ba131fa62f1254a9

test:
  secret_key_base: 70eff574235144d7ec62d55ff4e980179c4b2a0fbd38d6e942618c84ae701be5b28ed5183d4d5bfa15eb0587aef240a3c590dfa15bda82abc697bdd05b5a5f67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
